
package com.interview.practice.stub;

import com.interview.practice.*;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BasicMathServiceImplementerService", targetNamespace = "http://practice.interview.com/", wsdlLocation = "http://localhost:1234/basicMathService?wsdl")
public class BasicMathServiceImplementerService
    extends Service
{

    private final static URL BASICMATHSERVICEIMPLEMENTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException BASICMATHSERVICEIMPLEMENTERSERVICE_EXCEPTION;
    private final static QName BASICMATHSERVICEIMPLEMENTERSERVICE_QNAME = new QName("http://practice.interview.com/", "BasicMathServiceImplementerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/basicMathService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASICMATHSERVICEIMPLEMENTERSERVICE_WSDL_LOCATION = url;
        BASICMATHSERVICEIMPLEMENTERSERVICE_EXCEPTION = e;
    }

    public BasicMathServiceImplementerService() {
        super(__getWsdlLocation(), BASICMATHSERVICEIMPLEMENTERSERVICE_QNAME);
    }

    public BasicMathServiceImplementerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASICMATHSERVICEIMPLEMENTERSERVICE_QNAME, features);
    }

    public BasicMathServiceImplementerService(URL wsdlLocation) {
        super(wsdlLocation, BASICMATHSERVICEIMPLEMENTERSERVICE_QNAME);
    }

    public BasicMathServiceImplementerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASICMATHSERVICEIMPLEMENTERSERVICE_QNAME, features);
    }

    public BasicMathServiceImplementerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicMathServiceImplementerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BasicMathService
     */
    @WebEndpoint(name = "BasicMathServiceImplementerPort")
    public com.interview.practice.BasicMathService getBasicMathServiceImplementerPort() {
        return super.getPort(new QName("http://practice.interview.com/", "BasicMathServiceImplementerPort"), com.interview.practice.BasicMathService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BasicMathService
     */
    @WebEndpoint(name = "BasicMathServiceImplementerPort")
    public com.interview.practice.BasicMathService getBasicMathServiceImplementerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://practice.interview.com/", "BasicMathServiceImplementerPort"), com.interview.practice.BasicMathService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASICMATHSERVICEIMPLEMENTERSERVICE_EXCEPTION!= null) {
            throw BASICMATHSERVICEIMPLEMENTERSERVICE_EXCEPTION;
        }
        return BASICMATHSERVICEIMPLEMENTERSERVICE_WSDL_LOCATION;
    }

}
